package nicelee.bilibili.util;

import java.io.*;
import java.sql.*;
import java.util.*;

import org.json.JSONArray;
import org.json.JSONObject;

import nicelee.bilibili.model.DynamicItem;

/**
 * H2 嵌入式数据库：UP主动态目录 + 扫描状态 + 大文件待确认队列
 * 替代 CatalogUtil JSON 方案
 */
public class DynamicsDB {

	private static Connection conn;
	private static boolean dbAvailable = false;

	private static final String DB_PATH;

	static {
		String baseDir = ResourcesUtil.baseDirectory();
		DB_PATH = baseDir + "/config/dynamics";
	}

	public static void init() {
		try {
			Class.forName("org.h2.Driver");
			// 清理残留 lock 文件
			new File(DB_PATH + ".lock.db").delete();
			conn = DriverManager.getConnection(
				"jdbc:h2:file:" + DB_PATH + ";TRACE_LEVEL_FILE=0", "sa", "");
			createTables();
			migrateFromJson();
			dbAvailable = true;
			Logger.println("DynamicsDB initialized: " + DB_PATH);
		} catch (Exception e) {
			Logger.println("DynamicsDB init failed: " + e.getMessage());
			dbAvailable = false;
			conn = null;
		}
	}

	public static void shutdown() {
		dbAvailable = false;
		try { if (conn != null) conn.close(); } catch (Exception ignored) {}
	}

	// ===== 建表 =====
	private static void createTables() throws SQLException {
		try (Statement st = conn.createStatement()) {
			st.execute(
				"CREATE TABLE IF NOT EXISTS up_dynamics (" +
				"  dynamic_id VARCHAR(64) NOT NULL," +
				"  uid VARCHAR NOT NULL," +
				"  up_name VARCHAR," +
				"  type VARCHAR NOT NULL," +
				"  bvid VARCHAR," +
				"  title VARCHAR," +
				"  cover VARCHAR," +
				"  pub_timestamp BIGINT," +
				"  description VARCHAR," +
				"  duration_text VARCHAR," +
				"  downloaded INTEGER DEFAULT 0," +
				"  downloaded_at VARCHAR," +
				"  qn INTEGER," +
				"  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
				"  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
				"  PRIMARY KEY (uid, dynamic_id))");
			st.execute("CREATE INDEX IF NOT EXISTS idx_dyn_uid_time ON up_dynamics(uid, pub_timestamp DESC)");
			st.execute("CREATE INDEX IF NOT EXISTS idx_dyn_uid_dl ON up_dynamics(uid, downloaded)");
			st.execute("CREATE INDEX IF NOT EXISTS idx_dyn_bvid ON up_dynamics(bvid)");

			st.execute(
				"CREATE TABLE IF NOT EXISTS up_status (" +
				"  uid VARCHAR PRIMARY KEY," +
				"  up_name VARCHAR," +
				"  initial_scan_done INTEGER DEFAULT 0," +
				"  last_offset VARCHAR," +
				"  last_pub_timestamp BIGINT," +
				"  last_scan_time VARCHAR," +
				"  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
				"  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
			st.execute(
				"CREATE TABLE IF NOT EXISTS large_file_queue (" +
				"  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
				"  uid VARCHAR," +
				"  up_name VARCHAR," +
				"  bvid VARCHAR," +
				"  avid VARCHAR," +
				"  cid VARCHAR," +
				"  av_title VARCHAR," +
				"  cover VARCHAR," +
				"  estimated_size BIGINT," +
				"  url_query VARCHAR," +
				"  qn INTEGER," +
				"  real_qn INTEGER DEFAULT 0," +
				"  page INTEGER DEFAULT 0," +
				"  formatted_title VARCHAR," +
				"  status INTEGER DEFAULT 0," +
				"  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
		// 兼容旧表：补充缺失的列
		try { st.execute("ALTER TABLE large_file_queue ADD COLUMN avid VARCHAR"); } catch (Exception ignored) {}
		try { st.execute("ALTER TABLE large_file_queue ADD COLUMN cid VARCHAR"); } catch (Exception ignored) {}
		try { st.execute("ALTER TABLE large_file_queue ADD COLUMN real_qn INTEGER DEFAULT 0"); } catch (Exception ignored) {}
		try { st.execute("ALTER TABLE large_file_queue ADD COLUMN page INTEGER DEFAULT 0"); } catch (Exception ignored) {}
		}
	}

	// ===== 大文件队列 =====
	public static synchronized void insertLargeFile(String uid, String upName, String bvid, String avid, String cid, int realQN, int page,
			String avTitle, String cover, long estimatedSize, String urlQuery, int qn, String formattedTitle, int _realQN, int _page) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"INSERT INTO large_file_queue (uid, up_name, bvid, av_title, cover, estimated_size, url_query, qn, formatted_title)" +
				" VALUES (?,?,?,?,?,?,?,?,?)")) {
			ps.setString(1, uid);
			ps.setString(2, upName);
			ps.setString(3, bvid);
			ps.setString(4, avTitle);
			ps.setString(5, cover);
			ps.setLong(6, estimatedSize);
			ps.setString(7, urlQuery);
			ps.setInt(8, qn);
			ps.setString(9, formattedTitle);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	public static synchronized List<LargeFileItem> getPendingLargeFiles() {
		List<LargeFileItem> list = new ArrayList<>();
		if (!dbAvailable) return list;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT id, uid, up_name, bvid, avid, cid, av_title, cover, estimated_size, url_query, qn, real_qn, page, formatted_title, status," +
				" avid, cid, real_qn, page" +
				" FROM large_file_queue WHERE status=0 ORDER BY id")) {
			ResultSet rs = ps.executeQuery();
			while (rs.next()) {
				LargeFileItem item = new LargeFileItem();
				item.id = rs.getInt(1);
				item.uid = rs.getString(2);
				item.upName = rs.getString(3);
				item.bvid = rs.getString(4);
				item.avTitle = rs.getString(5);
				item.cover = rs.getString(6);
				item.estimatedSize = rs.getLong(7);
				item.urlQuery = rs.getString(8);
				item.qn = rs.getInt(9);
				item.formattedTitle = rs.getString(10);
				item.status = rs.getInt(11);
				item.avid = rs.getString(12);
				item.cid = rs.getString(13);
				item.realQN = rs.getInt(14);
				item.page = rs.getInt(15);
				list.add(item);
			}
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
		return list;
	}

	public static synchronized void markLargeFileDone(int id) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"UPDATE large_file_queue SET status=1 WHERE id=?")) {
			ps.setInt(1, id);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	public static synchronized void markLargeFileIgnored(int id) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"UPDATE large_file_queue SET status=-1 WHERE id=?")) {
			ps.setInt(1, id);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	public static synchronized int countPendingLargeFiles() {
		if (!dbAvailable) return 0;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT COUNT(*) FROM large_file_queue WHERE status=0")) {
			ResultSet rs = ps.executeQuery();
			return rs.next() ? rs.getInt(1) : 0;
		} catch (SQLException e) { return 0; }
	}

	// ===== 扫描状态 =====
	public static synchronized boolean isInitialScanDone(String uid) {
		if (!dbAvailable) return false;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT initial_scan_done FROM up_status WHERE uid=?")) {
			ps.setString(1, uid);
			ResultSet rs = ps.executeQuery();
			return rs.next() && rs.getInt(1) == 1;
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); return false; }
	}

	public static synchronized void markInitialScanDone(String uid, String upName) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"MERGE INTO up_status (uid, up_name, initial_scan_done, updated_at) VALUES (?,?,1,CURRENT_TIMESTAMP)")) {
			ps.setString(1, uid);
			ps.setString(2, upName);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	public static synchronized String getLastOffset(String uid) {
		if (!dbAvailable) return "";
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT last_offset FROM up_status WHERE uid=?")) {
			ps.setString(1, uid);
			ResultSet rs = ps.executeQuery();
			return rs.next() ? rs.getString(1) : "";
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); return ""; }
	}

	public static synchronized void setLastOffset(String uid, String upName, String offset, long lastPubTimestamp) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"MERGE INTO up_status (uid, up_name, last_offset, last_pub_timestamp, last_scan_time, updated_at)" +
				" VALUES (?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)")) {
			ps.setString(1, uid);
			ps.setString(2, upName);
			ps.setString(3, offset);
			ps.setLong(4, lastPubTimestamp);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	// ===== 查询 =====
	public static synchronized boolean contains(String uid, String dynamicId) {
		if (!dbAvailable) return false;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT 1 FROM up_dynamics WHERE uid=? AND dynamic_id=?")) {
			ps.setString(1, uid);
			ps.setString(2, dynamicId);
			return ps.executeQuery().next();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); return false; }
	}

	public static synchronized boolean containsBvid(String uid, String bvid) {
		if (!dbAvailable) return false;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT 1 FROM up_dynamics WHERE uid=? AND bvid=?")) {
			ps.setString(1, uid);
			ps.setString(2, bvid);
			return ps.executeQuery().next();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); return false; }
	}

	public static synchronized Set<String> getKnownBvids(String uid) {
		Set<String> set = new HashSet<>();
		if (!dbAvailable) return set;
		try (PreparedStatement ps = conn.prepareStatement(
				"SELECT bvid FROM up_dynamics WHERE uid=? AND bvid IS NOT NULL")) {
			ps.setString(1, uid);
			ResultSet rs = ps.executeQuery();
			while (rs.next()) set.add(rs.getString(1));
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
		return set;
	}

	// ===== 写入（批量 MERGE INTO） =====
	public static synchronized void insertDynamics(List<DynamicItem> items) {
		if (!dbAvailable || items.isEmpty()) return;
		String sql = "MERGE INTO up_dynamics (dynamic_id, uid, up_name, type, bvid, title, cover," +
			" pub_timestamp, description, duration_text, updated_at)" +
			" VALUES (?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)";
		try {
			conn.setAutoCommit(false);
			try (PreparedStatement ps = conn.prepareStatement(sql)) {
				int count = 0;
				for (DynamicItem item : items) {
					ps.setString(1, item.getDynamicId());
					ps.setString(2, item.getUid());
					ps.setString(3, item.getUpName());
					ps.setString(4, item.getType());
					ps.setString(5, item.getBvid());
					ps.setString(6, item.getTitle());
					ps.setString(7, item.getCover());
					if (item.getPubTimestamp() != null) ps.setLong(8, item.getPubTimestamp());
					else ps.setNull(8, Types.BIGINT);
					ps.setString(9, item.getDescription());
					ps.setString(10, item.getDurationText());
					ps.addBatch();
					if (++count % 50 == 0) { ps.executeBatch(); }
				}
				ps.executeBatch();
			}
			conn.commit();
		} catch (SQLException e) {
			dbAvailable = false;
			try { conn.rollback(); } catch (SQLException ignored) {}
			Logger.println("DynamicsDB insert: " + e.getMessage());
		} finally {
			try { conn.setAutoCommit(true); } catch (SQLException ignored) {}
		}
	}

	// ===== 下载状态 =====
	public static synchronized void markDownloaded(String uid, String bvid, int qn) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"UPDATE up_dynamics SET downloaded=1, downloaded_at=CURRENT_TIMESTAMP, qn=?, updated_at=CURRENT_TIMESTAMP" +
				" WHERE uid=? AND bvid=?")) {
			ps.setInt(1, qn);
			ps.setString(2, uid);
			ps.setString(3, bvid);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	public static synchronized void markDownloadFailed(String uid, String bvid) {
		if (!dbAvailable) return;
		try (PreparedStatement ps = conn.prepareStatement(
				"UPDATE up_dynamics SET downloaded=-1, updated_at=CURRENT_TIMESTAMP WHERE uid=? AND bvid=?")) {
			ps.setString(1, uid);
			ps.setString(2, bvid);
			ps.executeUpdate();
		} catch (SQLException e) { dbAvailable = false; Logger.println("DynamicsDB: " + e.getMessage()); }
	}

	// ===== 迁移 =====
	private static void migrateFromJson() {
		File catalogDir = new File(ResourcesUtil.baseDirectory(), "config/catalog");
		if (!catalogDir.exists() || !catalogDir.isDirectory()) return;
		File[] files = catalogDir.listFiles((d, n) -> n.endsWith(".json"));
		if (files == null || files.length == 0) return;

		int migrated = 0;
		for (File f : files) {
			try {
				String uid = f.getName().replace(".json", "");
				StringBuilder sb = new StringBuilder();
				try (BufferedReader r = new BufferedReader(new InputStreamReader(new FileInputStream(f), "utf-8"))) {
					String line; while ((line = r.readLine()) != null) sb.append(line);
				}
				JSONArray bvids = new JSONObject(sb.toString()).getJSONArray("bvids");
				String sql = "MERGE INTO up_dynamics (dynamic_id, uid, type, bvid, updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)";
				try (PreparedStatement ps = conn.prepareStatement(sql)) {
					for (int i = 0; i < bvids.length(); i++) {
						String bvid = bvids.getString(i);
						ps.setString(1, uid + "_" + bvid); // 合成唯一ID
						ps.setString(2, uid);
						ps.setString(3, "AV");
						ps.setString(4, bvid);
						ps.addBatch();
					}
					ps.executeBatch();
				}
				// 标记为已全扫
				try (PreparedStatement ps = conn.prepareStatement(
						"MERGE INTO up_status (uid, initial_scan_done, updated_at) VALUES (?,1,CURRENT_TIMESTAMP)")) {
					ps.setString(1, uid);
					ps.executeUpdate();
				}
				f.renameTo(new File(catalogDir, f.getName() + ".migrated"));
				migrated++;
			} catch (Exception e) {
				Logger.println("Migration failed for " + f.getName() + ": " + e.getMessage());
			}
		}
		if (migrated > 0) Logger.println("DynamicsDB: migrated " + migrated + " catalog files");
	}

	// ===== 大文件待确认项 =====
	public static class LargeFileItem {
		public int id;
		public String uid, upName, bvid, avid, cid, avTitle, cover, urlQuery, formattedTitle;
		public long estimatedSize;
		public int qn, realQN, page, status;
	}
}
